name = "MobilePererecos"
author = "Staff MinePererecos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9b9ed393a6221d7de9872a6064212cc9602dd3169d00abfecab40161b143a71"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
